developers sso into AWS
Shift3/dj-starter pull request #61
Opened 2023-04-03 06:08 UTC by tiruworktito

## Changes
1. Changed the provisioning infrastructure markdown to include sso 

## Purpose
Documentation between the onboarding assignment and the instructions on this repo are not the same.
 
## Approach
_How does this change address the problem?_
This PR addresses the difference between the two by adding in the same instructions from the onborarding assignment. 

## Pre-Testing TODOs
you should have the laptop script installed.

## Testing Steps
run the commands introduced. 

Closes #001

2023-04-03 21:35 UTC, fluturecode submitted a review, later dismissed
This looks fine to me. Nice work.

2023-04-04 16:43 UTC, michaelachrisco requested changes
Thanks for contributing @tiruworktito! Thanks for taking a look at anopther place our docs need to be updated. 

A couple of blockers: 

1. Please change the base to the `develop` branch. When we have new changes within the boilerplates, we should follow the S&P [git flow](https://github.com/Shift3/standards-and-practices#git) standards. Please do the following: 

![Change_branch_base](https://user-images.githubusercontent.com/398491/229858863-f12f4603-2940-4281-9871-84654422314b.gif)


2. Please remove the branch names from the markdown file. For example `nm-01-ssoconfigure` and `main` should be removed. 

3. Lets keep the same standard we have going in the Devops Apprentices Notes repository and include myself and the DevOps team on any new Pull Requests to the boilerplates. Please add @michaelachrisco and @BWTCDevops as reviewers. 
Let me know when you are finished with the above changes via slack or need any help. 

Appreciate you taking the initiative updating our docs! I know the first Pull Requests can be a bit difficult but you did great jumping in.

2023-04-04 16:43 UTC, michaelachrisco commented on docs/docs/deploying-your-app/01-provisioning-infrastructure.md
> +nm-01-ssoconfigure
What is this? A branch name?

2023-04-04 16:43 UTC, michaelachrisco commented on docs/docs/deploying-your-app/01-provisioning-infrastructure.md
> +main
Please remove branch names from the instructions.

2023-04-04 16:43 UTC, michaelachrisco commented on docs/docs/deploying-your-app/01-provisioning-infrastructure.md
> +(press inter)
```suggestion
(press enter)
```

2023-04-04 16:43 UTC, michaelachrisco commented on docs/docs/deploying-your-app/01-provisioning-infrastructure.md
> +nm-01-ssoconfigure
Please remove branch names from the instructions.

2023-04-04 16:43 UTC, michaelachrisco commented on docs/docs/deploying-your-app/01-provisioning-infrastructure.md
> +main
Same here.

2023-04-05 18:19 UTC, michaelachrisco requested changes
Thanks for dealing with the merge conflict and changing the base branch @tiruworktito !

Please take a look at the comments above for feedback. Let me know if you need any help with that or need direction!

2023-04-21 05:12 UTC, tiruworktito commented on docs/docs/deploying-your-app/01-provisioning-infrastructure.md
> +nm-01-ssoconfigure
not the name of the branch

2023-04-21 05:17 UTC, closed without merging